{% set name = "tiptop" %}
{% set version = "0.2.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tiptop-{{ version }}.tar.gz
  sha256: b8ef2910b9b64e9642a292e7e1a0c00e73421cdfe9967fa8a857467a168fe75f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - tiptop = tiptop._app:run

requirements:
  host:
    - distro
    - flit-core >=3.2,<4
    - pip
    - psutil
    - py-cpuinfo
    - python >=3.7
    - textual >=0.1.14,<0.2
  run:
    - psutil
    - python >=3.7
    - rich >=11.0.0
    - textual >=0.1.14,<0.2

test:
  source_files:
    - tests
  imports:
    - tiptop
  commands:
    - pip check
    - tiptop -h
    - pytest -vvv --capture=tee-sys tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/nschloe/tiptop
  summary: A command-line system monitoring tool in the spirit of top.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
